# Generated by Django 5.1.2 on 2025-06-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='local',
            new_name='location',
        ),
    ]
