# Generated by Django 5.1.2 on 2025-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
