# Generated by Django 5.1.2 on 2025-05-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appgroup_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('account_management|list_groups_and_roles', 'view groups and roles'), ('account_management|create_group_and_assign_roles', 'create new groups and assign roles'), ('account_management|update_groups_and_roles', 'update existing groups and their roles'), ('account_management|delete_groups_and_roles', 'delete groups and their roles'), ('account_management|create_admin', 'add admin'), ('account_management|list_admins', 'list admins'), ('account_management|delete_admin', 'delete admin'), ('account_management|update_admin', 'update admin'), ('shared_custom_types|create_custom_type', 'create custom type'), ('shared_custom_types|update_custom_type', 'update custom type'), ('shared_custom_types|delete_custom_type', 'delete custom type'), ('shared_app_settings|create_or_update_settings', 'create or update settings'), ('farm|create_farm', 'create a farm'), ('farm|update_farm', 'update a farm'), ('farm|delete_farm', 'delete a farm'), ('farm|view_farm', 'view a farm'), ('farm|list_farms', 'list all farms'), ('farm|delete_farm_products', 'remove a product from a farm'), ('farmer|create_farmer', 'create a farmer'), ('farmer|update_farmer', 'update a farmer'), ('farmer|delete_farmer', 'delete a farmer'), ('farmer|list_farmers', 'list all farmers'), ('farmer|view_farmer', 'view a farmer'), ('product|create_product', 'create a product'), ('product|update_product', 'update a product'), ('product|delete_product', 'delete a product'), ('product|list_products', 'list all products'), ('product|view_product', 'view a product'), ('credit|create_credit', 'create a credit'), ('credit|update_credit', 'update a credit'), ('credit|delete_credit', 'delete a credit'), ('credit|view_credit', 'view a credit'), ('credit|list_credits', 'list all credits'), ('credit|approve_deny_credit', 'approve or deny credit'), ('payback|create_payback', 'create a payback for a credit'), ('payback|update_payback', 'update a payback for a credit'), ('payback|list_paybacks', 'list all paybacks')]},
        ),
    ]
