# Generated by Django 5.1.2 on 2025-05-25 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_customer_id'),
        ('farm', '0009_alter_product_quantity'),
        ('organizations', '0001_initial'),
        ('warehouse', '0004_alter_warehouseproductmovement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutflowOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('outflow_order_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('availability_check', 'Availability Check'), ('truck_pickup', 'Truck Pickup'), ('delivered', 'Delivered'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='availability_check', max_length=20)),
                ('destination', models.CharField(max_length=255)),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('extra_comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('procurement_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflow_procurement_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outflow Order',
                'verbose_name_plural': 'Outflow Orders',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderDeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_phone_number', models.CharField(max_length=15)),
                ('driver_license_number', models.CharField(max_length=50)),
                ('truck_license_number', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('escort_required', models.BooleanField(default=False)),
                ('escort_details', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_information', to='outflow.outfloworder')),
            ],
            options={
                'verbose_name': 'Outflow Order Delivery Information',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderDeliveryInformationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='outflow/delivery_information/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order_delivery_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outflow.outfloworderdeliveryinformation')),
            ],
            options={
                'verbose_name': 'Outflow Order Delivery Information ',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderDeliveryInformationWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pick_up', models.BooleanField(default=False)),
                ('pick_up_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order_delivery_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='outflow.outfloworderdeliveryinformation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='outflow.outfloworder')),
            ],
            options={
                'verbose_name': 'Outflow Order History',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment')], default='full', max_length=20)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='outflow.outfloworder')),
            ],
            options={
                'verbose_name': 'Outflow Order Payment',
                'verbose_name_plural': 'Outflow Order Payments',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_quantity', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('not_enough_stock', 'Not Enough Stock'), ('order_pickup', 'Order Pickup'), ('complete', 'Complete')], default='verified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='outflow.outfloworder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'verbose_name': 'Outflow Order Warehouse',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderWarehouseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='outflow.outfloworderwarehouse')),
            ],
            options={
                'verbose_name': 'Outflow Order Warehouse History',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderWarehouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='outflow/warehouse/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outflow.outfloworderwarehouse')),
            ],
            options={
                'verbose_name': 'Outflow Order Warehouse Image',
            },
        ),
        migrations.CreateModel(
            name='OutflowOrderWarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('not_enough_stock', 'Not Enough Stock')], default='verified', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('outflow_order_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='outflow.outfloworderwarehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.product')),
            ],
            options={
                'verbose_name': 'Outflow Order Warehouse Product',
            },
        ),
    ]
