# Generated by Django 5.1.2 on 2025-05-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfloworder',
            old_name='outflow_order_id',
            new_name='order_id',
        ),
    ]
