# Generated by Django 5.1.2 on 2025-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0002_rename_outflow_order_id_outfloworder_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderwarehouseproduct',
            name='serial_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
