# Generated by Django 5.1.2 on 2025-05-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0003_outfloworderwarehouseproduct_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfloworderwarehouseproduct',
            name='available_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outfloworderwarehouseproduct',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('not_enough_stock', 'Not Enough Stock')], default='pending_verification', max_length=20),
        ),
    ]
