# Generated by Django 5.1.2 on 2025-05-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_product_quantity'),
        ('outflow', '0004_alter_outfloworderwarehouseproduct_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfloworderwarehouse',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('not_enough_stock', 'Not Enough Stock'), ('order_pickup', 'Order Pickup'), ('complete', 'Complete')], default='pending_verification', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='outfloworderwarehouseproduct',
            unique_together={('outflow_order_warehouse', 'product')},
        ),
    ]
