# Generated by Django 5.1.2 on 2025-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0005_alter_outfloworderwarehouse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderwarehouseproduct',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outfloworderwarehouseproduct',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
