# Generated by Django 5.1.2 on 2025-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0006_outfloworderwarehouseproduct_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfloworder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('availability_check', 'Availability Check'), ('truck_pickup', 'Truck Pickup'), ('delivered', 'Delivered'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
