# Generated by Django 5.1.2 on 2025-06-24 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0007_alter_outfloworder_status'),
        ('warehouse', '0007_merge_20250624_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfloworderdeliveryinformationwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflow_delivery_warehouse', to='warehouse.warehouse'),
        ),
    ]
