# Generated by Django 5.1.2 on 2025-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0008_alter_outfloworderdeliveryinformationwarehouse_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderpayments',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outfloworderpayments',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='outfloworderpayments',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outfloworderpayments',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='outfloworderpayments',
            name='paid_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
