# Generated by Django 5.1.2 on 2025-06-25 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0009_outfloworderpayments_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfloworderpayments',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
