# Generated by Django 5.1.2 on 2025-07-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0010_alter_outfloworderpayments_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworder',
            name='additional_cost_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='outfloworder',
            name='additional_costs',
            field=models.TextField(blank=True),
        ),
    ]
