# Generated by Django 5.1.2 on 2025-07-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0012_outflowrecipientcomplaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderwarehousehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='outflow.outfloworderwarehouseproduct'),
        ),
    ]
