# Generated by Django 5.1.2 on 2025-07-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0014_outfloworder_waybill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderpayments',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
