# Generated by Django 5.1.2 on 2025-08-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0015_outfloworderpayments_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworder',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='outfloworderwarehouse',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='outfloworderwarehouseproduct',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
