# Generated by Django 5.1.2 on 2025-08-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0016_outfloworder_total_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworderhistory',
            name='event_type',
            field=models.CharField(choices=[('availability_check', 'Availability Check'), ('truck_pickup', 'Truck Pickup'), ('delivered', 'Delivered'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('approved', 'Approved')], default='availability_check', max_length=100),
        ),
        migrations.AddField(
            model_name='outfloworderhistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
