# Generated by Django 5.1.2 on 2025-08-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0017_outfloworderhistory_event_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfloworderhistory',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='outfloworderhistory',
            name='notes',
        ),
    ]
