# Generated by Django 5.1.2 on 2025-09-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0018_remove_outfloworderhistory_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfloworder',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='outfloworder',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
