# Generated by Django 5.1.2 on 2025-05-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0002_infloworder_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infloworderproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
