# Generated by Django 5.1.2 on 2025-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0003_alter_infloworderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infloworder',
            name='order_creation_date',
            field=models.DateField(),
        ),
    ]
