# Generated by Django 5.1.2 on 2025-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0004_alter_infloworder_order_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='infloworder',
            name='total_product_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
