# Generated by Django 5.1.2 on 2025-05-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0005_infloworder_total_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infloworder',
            name='status',
            field=models.CharField(choices=[('delivery_inspection', 'Delivery Inspection'), ('order_approval', 'Order Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='delivery_inspection', max_length=20),
        ),
    ]
