# Generated by Django 5.1.2 on 2025-05-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0006_alter_infloworder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infloworder',
            old_name='total_product_cost',
            new_name='total_products_cost',
        ),
    ]
