# Generated by Django 5.1.2 on 2025-05-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0007_rename_total_product_cost_infloworder_total_products_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infloworderhistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='infloworderhistory',
            name='user',
        ),
    ]
