# Generated by Django 5.1.2 on 2025-07-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0008_remove_infloworderhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infloworder',
            name='waybill_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
