# Generated by Django 5.1.2 on 2025-07-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inflow", "0009_infloworder_waybill_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="infloworder",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
