# Generated by Django 5.1.2 on 2025-07-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0010_infloworder_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infloworder',
            name='invoice_id',
        ),
    ]
