# Generated by Django 5.1.2 on 2025-08-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0011_remove_infloworder_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='infloworder',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='infloworderproduct',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
