# Generated by Django 5.1.2 on 2025-08-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0012_infloworder_total_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infloworder',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
