# Generated by Django 5.1.2 on 2025-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0013_alter_infloworder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infloworderhistory',
            name='event_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('document_upload', 'Document Up load')], max_length=20),
        ),
    ]
