# Generated by Django 5.1.2 on 2025-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0014_alter_infloworderhistory_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infloworder',
            name='actual_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='infloworder',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
