# Generated by Django 5.1.2 on 2026-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_integrationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
