# Generated by Django 5.1.2 on 2025-09-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_expense_actual_amount_expense_expected_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expected_amount',
        ),
    ]
