# Generated by Django 5.1.2 on 2025-05-17 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflow', '0001_initial'),
        ('warehouse', '0002_warehouseproductmovement_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductmovement',
            name='inflow_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inflow.infloworder'),
        ),
    ]
