# Generated by Django 5.1.2 on 2025-05-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouseproductmovement_inflow_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproductmovement',
            options={'ordering': ['-record_date']},
        ),
        migrations.RemoveField(
            model_name='warehouseproductmovement',
            name='date',
        ),
        migrations.AddField(
            model_name='warehouseproductmovement',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
