# Generated by Django 5.1.2 on 2025-06-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehouseproductmovement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='district',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='region',
        ),
    ]
