# Generated by Django 5.1.2 on 2025-05-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflow', '0003_outfloworderwarehouseproduct_serial_number'),
        ('warehouse', '0004_alter_warehouseproductmovement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductmovement',
            name='outflow_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='outflow.outfloworder'),
        ),
    ]
