# Generated by Django 5.1.2 on 2025-06-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_region_district'),
        ('warehouse', '0005_remove_warehouse_district_remove_warehouse_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.district'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.region'),
        ),
    ]
