# Generated by Django 5.1.2 on 2025-06-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehouseproductmovement_outflow_order'),
        ('warehouse', '0006_warehouse_district_warehouse_region'),
    ]

    operations = [
    ]
