# Generated by Django 5.1.2 on 2025-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_warehouseproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproductmovement',
            name='movement_type',
            field=models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=7),
        ),
    ]
