# Generated by Django 5.1.2 on 2025-07-13 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_local_customer_location'),
        ('warehouse', '0009_alter_warehouseproductmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproductmovement',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customers.customer'),
        ),
    ]
