# Generated by Django 5.1.2 on 2025-07-25 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_warehouseproductmovement_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='manager',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
