# Generated by Django 5.1.2 on 2025-09-02 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_remove_credit_input_credits_remove_credit_type_and_more'),
        ('warehouse', '0012_inputcreditwarehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCreditWarehouseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=7)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('inflow_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_credit_movements', to='credit.inputcreditpurchase')),
                ('input_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_credit_warehouse_movements', to='credit.inputcredit')),
                ('input_credit_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_credit_warehouse_movements', to='warehouse.inputcreditwarehouse')),
                ('outflow_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_credit_movements', to='credit.credit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_credit_warehouse_movements', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
    ]
