# Generated by Django 5.1.2 on 2025-09-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_inputcreditwarehousemovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcreditwarehousemovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseproductmovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
