# Generated by Django 5.1.2 on 2025-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_department_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='comments',
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='probation',
            field=models.BooleanField(default=False),
        ),
    ]
