# Generated by Django 5.1.2 on 2025-07-26 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_employeecontract_employeedisciplinaryaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.department'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.jobtitle'),
        ),
    ]
