# Generated by Django 5.1.2 on 2025-07-26 18:09

import apps.shared.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employeecontract_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeemergencycontact',
            name='phone_number',
            field=models.CharField(max_length=40, null=True, validators=[django.core.validators.MinLengthValidator(11, 'Phone number number must be at least 11 characters.'), apps.shared.utils.validators.validate_only_digits]),
        ),
    ]
