# Generated by Django 5.1.2 on 2025-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_training_trainingattendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_mode',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'Offline')], max_length=20),
        ),
    ]
