# Generated by Django 5.1.2 on 2025-07-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_department_status_alter_training_training_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='all_employees',
            field=models.BooleanField(default=False),
        ),
    ]
