# Generated by Django 5.1.2 on 2025-07-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_leavetype_leaverequest'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
