# Generated by Django 5.1.2 on 2025-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
