# Generated by Django 5.1.2 on 2025-07-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_leaverequest_action_taken_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='action_taken_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
