# Generated by Django 5.1.2 on 2025-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_alter_leaverequest_action_taken_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='notification',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='phone_number', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
