# Generated by Django 5.1.2 on 2025-08-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employee_notification_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='notification',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Rejected'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
