# Generated by Django 5.1.2 on 2025-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_alter_employee_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='attendance_completed',
            field=models.BooleanField(default=False),
        ),
    ]
