# Generated by Django 5.1.2 on 2025-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_training_attendance_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='attendance_completed',
        ),
        migrations.AddField(
            model_name='training',
            name='attendance_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20),
        ),
    ]
