# Generated by Django 5.1.2 on 2025-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_remove_training_attendance_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed')], default='active', max_length=20),
        ),
    ]
