# Generated by Django 5.1.2 on 2025-09-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='ssnit_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
