# Generated by Django 5.1.2 on 2025-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_employeecontract_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_profile_pics/'),
        ),
    ]
