# Generated by Django 5.1.2 on 2025-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_employee_ghana_card_number_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ghana_card_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
