# Generated by Django 5.1.2 on 2025-09-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_alter_employee_ghana_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontract',
            name='ssnit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
