# Generated by Django 5.1.2 on 2026-06-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='message_id',
        ),
    ]
