# Generated by Django 5.1.2 on 2026-06-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_remove_smslog_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='purpose',
            field=models.CharField(choices=[('farmer-registration', 'farmer-registration')], default='farmer-registration', max_length=120),
        ),
    ]
