# Generated by Django 5.1.2 on 2025-05-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season_status',
            field=models.CharField(choices=[('in', 'In Season'), ('out', 'Out of Season')], default='in', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
