# Generated by Django 5.1.2 on 2025-05-08 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_product_season_status_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='areas_of_assistance',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to='farm.farmer'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farming_methods',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='irrigation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='use_of_fertilizers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
