# Generated by Django 5.1.2 on 2025-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_farm_areas_of_assistance_alter_farm_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_id',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
