# Generated by Django 5.1.2 on 2025-05-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_farmer_farmer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock')], max_length=20),
        ),
    ]
