# Generated by Django 5.1.2 on 2025-05-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_product_quantity_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season_status',
            field=models.CharField(blank=True, choices=[('in', 'In Season'), ('out', 'Out of Season')], max_length=10, null=True),
        ),
    ]
