# Generated by Django 5.1.2 on 2025-05-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_product_season_status'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_name': 'product_category'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='shared.customtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_metric',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_name': 'quantity_metric'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_quantity_metrics', to='shared.customtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_metric',
            field=models.ForeignKey(blank=True, limit_choices_to={'category_name': 'weight_metric'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_weight_metrics', to='shared.customtype'),
        ),
    ]
