# Generated by Django 5.1.2 on 2025-06-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_product_quantity'),
        ('shared', '0002_region_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='size_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_size_metrics', to='shared.customtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='shared.customtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_quantity_metrics', to='shared.customtype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_weight_metrics', to='shared.customtype'),
        ),
    ]
