# Generated by Django 5.1.2 on 2025-06-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_alter_farm_size_metric_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='district',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='district',
        ),
    ]
