# Generated by Django 5.1.2 on 2025-06-03 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0011_remove_farm_district_remove_farmer_district'),
        ('shared', '0002_region_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='shared.district'),
        ),
        migrations.AddField(
            model_name='farm',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='shared.region'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='shared.district'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='shared.region'),
        ),
    ]
