# Generated by Django 5.1.2 on 2025-06-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_farm_district_farm_region_farmer_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
