# Generated by Django 5.1.2 on 2025-07-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0013_farmer_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
