# Generated by Django 5.1.2 on 2025-07-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0014_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
