# Generated by Django 5.1.2 on 2025-07-27 21:29

import apps.shared.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0015_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(max_length=40, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'Phone number number must be at least 11 characters.'), apps.shared.utils.validators.validate_only_digits]),
        ),
    ]
