# Generated by Django 5.1.2 on 2025-07-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0016_alter_farmer_email_alter_farmer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('crop', 'Crop'), ('other', 'Other')], max_length=20),
        ),
    ]
