# Generated by Django 5.1.2 on 2025-08-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0017_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_products', to='farm.farm'),
        ),
        migrations.AlterField(
            model_name='farmproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_products', to='farm.product'),
        ),
    ]
