# Generated by Django 5.1.2 on 2025-08-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0018_alter_farmproduct_farm_alter_farmproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmproduct',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
        ),
        migrations.AlterField(
            model_name='farmproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.product'),
        ),
    ]
