# Generated by Django 5.1.2 on 2025-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0021_product_manager_id_product_manager_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='manager_id',
            field=models.CharField(blank=True, help_text='The unique key from the external Manager.io system.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='manager_json_data',
            field=models.JSONField(blank=True, help_text='A cached copy of the last known data from Manager.io.', null=True),
        ),
    ]
