# Generated by Django 5.1.2 on 2025-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0022_farm_manager_id_farm_manager_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
