# Generated by Django 5.1.2 on 2026-06-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0026_farmerregistrationrequest_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerregistrationrequest',
            old_name='approved_at',
            new_name='reviewed_at',
        ),
        migrations.RenameField(
            model_name='farmerregistrationrequest',
            old_name='approved_by',
            new_name='reviewed_by',
        ),
    ]
