# Generated by Django 5.1.2 on 2026-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0027_rename_approved_at_farmerregistrationrequest_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistrationrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
