# Generated by Django 5.1.2 on 2026-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0028_farmerregistrationrequest_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistrationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='farmerregistrationrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
