# Generated by Django 5.1.2 on 2026-06-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0029_alter_farmerregistrationrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
