from enum import Enum


class UssdSteps(str, Enum):
    USSD_INIT = "USSD_INIT"
    FARM_REG_U_INIT = "FARM_REG_U_INIT"
    FARM_REG_INIT = "FARM_REG_INIT"
    ID_NUMBER = "ID_NUMBER"
    FIRST_NAME = "FIRST_NAME"
    LAST_NAME = "LAST_NAME"
    GENDER="GENDER"
    DOB = "DOB"
    REGION = "REGION"
    DISTRICT = "DISTRICT"
    FARM_SIZE = "FARM_SIZE"
    CONFIRM_FARM_REG = "CONFIRM_FARM_REG"
    USSD_END = "USSD_END"
class UssdFlowType(str, Enum):
    USSD_INIT = "USSD_INIT"
    FARM_REG_U = "FARM_REG_U"
    FARM_REG = "FARM_REG"
