# Generated by Django 5.1.2 on 2025-05-11 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0008_alter_product_category_alter_product_quantity_metric_and_more'),
        ('organizations', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_id', models.CharField(max_length=50, unique=True)),
                ('input_credits', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('hybrid_seed', 'Hybrid Seed'), ('agro_chemicals', 'Agro Chemicals'), ('mechanisation', 'Mechanisation(Ploughing)')], max_length=20)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('denial_notes', models.TextField(blank=True, null=True)),
                ('main_crops', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('quantity_metric', models.ForeignKey(blank=True, limit_choices_to={'category_name': 'quantity_metric'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_quantity_metrics', to='shared.customtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditPayback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payback_method', models.CharField(blank=True, choices=[('cash_payback', 'Cash Payback'), ('crop_exchange', 'Crop Exchange')], help_text='Select payment method - cash or crop exchange', max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being paid back in GHe', max_digits=10)),
                ('outstanding_before', models.DecimalField(decimal_places=2, help_text='Outstanding amount before this payment', max_digits=10)),
                ('outstanding_after', models.DecimalField(decimal_places=2, help_text='Outstanding amount after this payment', max_digits=10)),
                ('quantity_bags', models.IntegerField(blank=True, help_text='Number of bags/units exchanged', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True, help_text='Additional notes about this payment', null=True)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial')], default='paid', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paybacks', to='credit.credit')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('product', models.ForeignKey(blank=True, help_text='Product traded in crop exchange (e.g. Maize)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('status_change', 'Status Change'), ('amount_change', 'Amount Change'), ('payment_created', 'Payment Created'), ('payment_updated', 'Payment Updated')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='credit.credit')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('payback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.creditpayback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
