# Generated by Django 5.1.2 on 2025-05-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditchangelog',
            name='event',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('status_change', 'Status Change'), ('amount_change', 'Amount Change'), ('payment_created', 'Payment Created'), ('payment_updated', 'Payment Updated'), ('field_updated', 'Field Updated')], max_length=20),
        ),
    ]
