# Generated by Django 5.1.2 on 2025-06-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_alter_creditchangelog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='self_application',
            field=models.BooleanField(default=False),
        ),
    ]
