# Generated by Django 5.1.2 on 2025-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_credit_self_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
