# Generated by Django 5.1.2 on 2025-09-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_remove_credit_input_credits_remove_credit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputcredit',
            name='input_credit_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
