# Generated by Django 5.1.2 on 2025-09-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_inputcredit_input_credit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='outstanding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('active', 'Active'), ('inactive', 'Inactive'), ('fulfilled', 'Fulfilled')], default='inactive', max_length=20),
        ),
    ]
