# Generated by Django 5.1.2 on 2025-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_alter_credit_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditwarehouse',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
