# Generated by Django 5.1.2 on 2025-09-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_creditwarehouse_is_fulfilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcredit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inputcredit',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inputcredit',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
