# Generated by Django 5.1.2 on 2025-09-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_alter_inputcredit_price_alter_inputcredit_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending'), ('fulfilled', 'Fulfilled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='credit',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue'), ('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
    ]
