# Generated by Django 5.1.2 on 2026-06-24 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_step', models.CharField(choices=[('USSD_INIT', 'USSD_INIT'), ('FARM_REG_U_INIT', 'FARM_REG_U_INIT'), ('FARM_REG_INIT', 'FARM_REG_INIT'), ('CHOOSE_ID', 'CHOOSE_ID'), ('ID_NUMBER', 'ID_NUMBER'), ('FIRST_NAME', 'FIRST_NAME'), ('LAST_NAME', 'LAST_NAME'), ('DOB', 'DOB'), ('REGION', 'REGION'), ('DISTRICT', 'DISTRICT'), ('FARM_SIZE', 'FARM_SIZE'), ('CONFIRM_FARM_REG', 'CONFIRM_FARM_REG'), ('COMPLETE', 'COMPLETE'), ('END', 'END')], default='USSD_INIT', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('flow_type',models.CharField(choices=[('USSD_INIT','USSD_INIT'),('FARM_REG_U','FARM_REG_U'),('FARM_REG','FARM_REG')], default='USSD_INIT', max_length=100)),
                ('history', models.JSONField(default=list)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('page_size', models.PositiveIntegerField(default=10)),
                ('expires_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
