# Generated by Django 5.1.2 on 2026-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='current_step',
            field=models.CharField(choices=[('USSD_INIT', 'USSD_INIT'), ('FARM_REG_U_INIT', 'FARM_REG_U_INIT'), ('FARM_REG_INIT', 'FARM_REG_INIT'), ('ID_NUMBER', 'ID_NUMBER'), ('FIRST_NAME', 'FIRST_NAME'), ('LAST_NAME', 'LAST_NAME'), ('DOB', 'DOB'), ('REGION', 'REGION'), ('DISTRICT', 'DISTRICT'), ('FARM_SIZE', 'FARM_SIZE'), ('CONFIRM_FARM_REG', 'CONFIRM_FARM_REG')], default='USSD_INIT', max_length=100),
        ),
    ]
