# Generated by Django 5.1.2 on 2026-06-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_alter_ussdsession_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='current_step',
            field=models.CharField(choices=[('USSD_INIT', 'USSD_INIT'), ('FARM_REG_U_INIT', 'FARM_REG_U_INIT'), ('FARM_REG_INIT', 'FARM_REG_INIT'), ('ID_NUMBER', 'ID_NUMBER'), ('FIRST_NAME', 'FIRST_NAME'), ('LAST_NAME', 'LAST_NAME'), ('GENDER', 'GENDER'), ('DOB', 'DOB'), ('REGION', 'REGION'), ('DISTRICT', 'DISTRICT'), ('FARM_SIZE', 'FARM_SIZE'), ('CONFIRM_FARM_REG', 'CONFIRM_FARM_REG'), ('USSD_END', 'USSD_END')], default='USSD_INIT', max_length=100),
        ),
    ]
